### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/code-fighters#6]
Hola chicas,

el fichero https://github.com/Adalab/code-fighters/blob/master/_src/templates/partials/_head.html  empieza con:
```javascript
<!DOCTYPE html>
<html lang="es">
```
y termina con 
```javascript
</html>
```

Esto está haciendo que la página tenga dos doctypes, dos html de apertura y dos html de cierre.

Es una buena práctica que si el fichero se llama _head el código que tenga dentro de este fichero empiece abriendo el head y termine cerrándolo.

Por favor cuanto tengáis tiempo, apañarlo. Si tenéis dudas mirad los proyectos de otros equipos o preguntadme.

Gracias.

**Comment by btdvalle** [comment]
Ya estaría.

**Comment by migueldelmazo** [comment]
Guay qué rapidez!!!

Podríamos actualizar la carpeta docs???

Cuando lo hagáis cerrad esta issue.

Ale buenas vacaciones!!!
